### ISSUE TITLE
Allow for chained commands to be sent to the sbt-client

### ISSUE THREAD

**Issue by dmarticus** [cb372/sbt-client#8]
One of the things that I like about the `sbt` shell is that I can sent semicolon-separated list of commands (e.g. `;clean;compile;test`), and sbt will run those commands in series.  It would be awesome if `sbt-client` could do the same thing (e.g. `sbt-client clean;compile;test`). 

I _think_ it's a simple fix?  It looks like you can just update the `run` method here: https://github.com/cb372/sbt-client/blob/master/src/main.rs#L38 to accept a string array, rather than a single string, and then dispatch a list of commands to the stream.  I think you'd want to update the the variable `sbt_command_line` (https://github.com/cb372/sbt-client/blob/master/src/main.rs#L26) to split on semicolons, rather than join on whitespace.

I've never touched Rust before and don't want to screw something up, so I don't have a fix for this now (I imagine you know a lot more and could probably do this faster than me), but I can take a crack at this tonight after work if you think it's worth the time.

Thanks for writing this!

**Comment by dwijnand** [comment]
You'd need to escape it because the shell would interpret `sbt-client clean;compile;test` as `sbt-client clean` and then try to run `compile` (and fail probably).

`sbt-client ';clean;compile;test'` I would assume already works as intended today.

**Comment by dmarticus** [comment]
Ahhh, yup!  You're exactly right, thanks for taking the time to take a look!
