### ISSUE TITLE
Released files could not execute on linux

### ISSUE THREAD

**Issue by kadzuya** [cb372/sbt-client#9]
I saw error on Ubuntu 18.04 LTS.
 (runs on CircleCI or GitHub Actions)

```
$ wget 'https://github.com/cb372/sbt-client/releases/download/v0.1.1/sbt-client'
$ chmod +x sbt-client
$ ./sbt-client compile

-bash: ./sbt-client: cannot execute binary file: Exec format error
```

But files created with `cargo install` on Ubuntu can be executed.

**Comment by cb372** [comment]
Sorry, this is expected behaviour. From the README:

>If you are on a Mac and you trust me enough to download a random binary file when I tell you to, you can download the binary from the GitHub release.

The binary file attached to the release is one that I have built locally on my Mac.

Ideally we should build binaries for all platforms on Travis CI and push them to GitHub automatically.

**Comment by kadzuya** [comment]
Thank you for answering!

I made a sample Github Action that builds a binary and upload it to the GitHub Release.
I think we can build binaries for many platforms with rustup or cross. 

I'm not familiar with rust, so this sample builds only for `x86_64-apple-darwin.gz
553`  and `x86_64-unknown-linux-gnu`.


- diff
https://github.com/cb372/sbt-client/compare/master...kadzuya:ci_build?expand=1
- GitHub Action log
https://github.com/kadzuya/sbt-client/commit/4bce3f35f6ef1128df2ff6e670e4cc8da28457a0/checks?check_suite_id=245988783
- Release page 
https://github.com/kadzuya/sbt-client/releases/tag/test

**Comment by kadzuya** [comment]
@cb372  Will we be able to download binaries from GitHub?

**Comment by cb372** [comment]
Hey, sorry for the slow reply.

This is great! I've never used GitHub Actions before. It looks really nice. I'd like to migrate the PR verification pipeline from Travis to GitHub Actions as well.

I've made a PR from your branch. It looks fine to me (I've tested the macOS binary), so I'll merge it and make a release now.

**Comment by cb372** [comment]
It works! 🎉https://github.com/cb372/sbt-client/releases/tag/v0.1.2

Thanks for your contribution.
